export default {
  common: {
    cancel: 'Cancel',
    delete: 'Delete',
    save: 'Save',
    edit: 'Edit',
    update: 'Update',
    close: 'Close',
    error: 'Error',
    success: 'Success',
    selectCustomer: 'Select customer',
    noCustomersFound: 'No customers found.',
    selectCustomerTitle: 'Select Customer',
    cash: 'Cash',
    upi: 'UPI',
    card: 'Card',
    netBanking: 'Net Banking',
    paid: 'PAID',
    pending: 'PENDING',
    required: 'Required',
    deleteInvoiceTitle: 'Delete Invoice',
    deleteInvoiceMessage: 'Are you sure you want to delete this invoice?',
    invoiceDeleted: 'Invoice deleted successfully',
    failedDeleteInvoice: 'Failed to delete invoice ',
  },

  stepIndicator: {
    customer: 'Customer',
    products: 'Products',
    summary: 'Summary',
  },

  bottomNav: {
    home: 'Home',
    create: 'Create',
    labour: 'Labour',
    invoices: 'Invoices',
  },

  splash: {
    companyLine1: 'Aadhi Engine',
    companyLine2: 'Services',
    tagline: 'ONLINE BILLING SYSTEM',
    loadingTexts: [
      'Initializing System...',
      'Connecting Services...',
      'Loading Modules...',
      'Preparing Dashboard...',
      'Almost Ready...',
    ],
  },

  login: {
    companyName: 'Aadhi Engine Services',
    welcomeBack: 'Welcome Back',
    enterPin: 'Enter your 4-digit PIN to continue',
    somethingWrong: 'Something went wrong',
    wrongPin: 'Wrong PIN',
    onlineBillingSystem: 'ONLINE BILLING SYSTEM',
    designedBy: 'Designed & Developed by Shanmugapriya Iyappan',
    deleteKey: 'Delete',
    keyLabel: 'Key {{label}}',
  },

  settings: {
    title: 'Settings',
    dataManagement: 'DATA MANAGEMENT',
    backupData: 'Backup Data',
    exportInvoices: 'Export Invoices (.JSON)',
    restoreBackup: 'Restore Backup',
    systemMaintenance: 'SYSTEM MAINTENANCE',
    deleteAllReports: 'Delete All Reports',
    logout: 'Logout',
    logoutConfirmTitle: 'Are you sure?',
    logoutConfirmMessage: 'You will be logged out of the system.',
    footer: 'Aadhi Engine Service v1.0.0 (Build 2026)',
    language: 'LANGUAGE',
    appLanguage: 'App Language',
    english: 'English',
    tamil: 'தமிழ்',
  },

  dashboard: {
    title: 'Dashboard',
    subtitle: 'Aadhi Engine Service',
    quickActions: 'QUICK ACTIONS',
    productInvoice: 'Product Invoice',
    labourInvoices: 'Labour Invoices',
    totalInvoices: 'Total Invoices',
    totalRevenue: 'Total Revenue',
    customers: 'Customers',
    monthlySummary: 'MONTHLY SUMMARY',
    performance: '{{month}} Performance',
    recentInvoices: 'RECENT INVOICES',
    viewAll: 'View All',
    noInvoicesYet: 'No invoices yet',
    unknownCustomer: 'Unknown Customer',
    changeThisMonth: '{{value}}% this month',
  },

  customerList: {
    title: 'Customers',
    record: 'record',
    records: 'records',
    searchPlaceholder: 'Search by name, mobile or address',
    resultsFor: '{{count}} {{resultWord}} for "{{query}}"',
    result: 'result',
    results: 'results',
    noResultsFound: 'No results found',
    noCustomersYet: 'No customers yet',
    nothingMatched: 'Nothing matched "{{query}}"',
    tapToAdd: 'Tap + to add your first customer',
    deleteCustomerTitle: 'Delete Customer?',
    deleteCustomerMessage:
      '"{{name}}" will be permanently removed. This cannot be undone.',
  },

  createCustomer: {
    editTitle: 'Edit Customer',
    addTitle: 'Add Customer',
    subtitle: 'Aadhi Engine Service',
    heading: 'Customer Details',
    descriptionEdit: 'Update the customer information below',
    descriptionAdd: 'Fill in the details below to add a new customer',
    customerName: 'Customer Name',
    enterFullName: 'Enter full name',
    mobileNumber: 'Mobile Number',
    optional: '(Optional)',
    enter10Digit: 'Enter 10-digit number',
    address: 'Address',
    enterAddress: 'Enter street, city, state...',
    updating: 'Updating....',
    saving: 'Saving....',
    updateCustomer: 'Update Customer',
    saveCustomer: 'Save Customer',
    discardTitle: 'Discard Changes?',
    discardMessage: 'Your changes will not be saved. Do you want to exit?',
    discard: 'Discard',
    keepEditing: 'Keep Editing',
    deleteCustomerTitle: 'Delete Customer?',
    deleteCustomerMessage:
      '"{{name}}" will be permanently removed. This cannot be undone.',
    nameRequired: 'Customer name is required',
    mobileDigits: 'Mobile number must be 10 digits',
    addressRequired: 'Address is required',
  },

  invoiceForm: {
    editInvoice: 'Edit Invoice',
    createInvoice: 'Create Invoice',
    editLabourInvoice: 'Edit Labour Invoice',
    createLabourInvoice: 'Create Labour Invoice',
    customerName: 'Customer Name',
    paymentReceived: 'Payment Received',
    paymentMode: 'Payment Mode',
    selectPaymentMode: 'Select Payment Mode',
    invoiceDate: 'Invoice Date',
    billNo: 'Bill No',
    addProduct: 'Add Product',
    addItem: 'Add Item',
    productNamePlaceholder: 'Product name',
    descriptionPlaceholder: 'Description',
    amountPlaceholder: 'Amount',
    qty: 'Qty',
    unitPrice: 'Unit Price',
    addProductBtn: '＋ Add Product',
    addItemBtn: '＋ Add Item',
    items: 'ITEMS ({{count}})',
    save: 'Save',
    grandTotal: 'Grand Total',
    updateBill: 'Update Bill',
    generateBill: 'Generate Bill',
    pleaseSelectCustomer: 'Please select customer',
    addAtLeastOneProduct: 'Add at least one product',
    addAtLeastOneItem: 'Add at least one item',
    invoiceUpdated: 'Invoice updated successfully ',
    invoiceCreated: 'Invoice Created',
    labourInvoiceUpdated: 'Labour Invoice updated successfully ',
    labourInvoiceCreated: 'Labour Invoice Created ',
  },

  invoiceList: {
    billNoPrefix: 'Bill No :{{no}}',
    total: 'Total',
    unknownCustomer: 'Unknown Customer',
    items: 'Items',
    itemCount: '{{count}} {{itemWord}}',
    item: 'item',
    itemsWord: 'items',
    tapToView: 'Tap to view invoice details',
    noInvoicesFound: 'No Invoices Found',
    createFirst: 'Create your first invoice to get started.',
    adjustFilters: 'Try adjusting your filters or search query.',
    clearAllFilters: 'Clear All Filters',
    searchPlaceholder: 'Search by code, customer, or mobile...',
    filters: 'Filters',
    paymentStatus: 'Payment Status',
    invoiceType: 'Invoice Type',
    dateRange: 'Date Range',
    clearAll: 'Clear All',
    applyFilters: 'Apply Filters',
    all: 'ALL',
    product: 'PRODUCT',
    labour: 'LABOUR',
  },

  invoicePreview: {
    title: 'Invoice Preview',
    companySubtitle: 'Aadhi Engine Care',
    billNo: 'Bill No:',
    date: 'Date:',
    customerDetails: 'Customer Details',
    to: 'To',
    noPhoneAvailable: 'No phone number available',
    paymentMode: 'Payment Mode',
    sNo: 'S.No',
    descriptionCol: 'Description',
    qty: 'Qty',
    rate: 'Rate',
    amount: 'Amount',
    total: 'Total',
    amountInWords: 'Amount in words',
    sign: 'Sign',
    markAsPaid: 'Mark as Paid',
    generatingPdf: 'Generating PDF...',
    previewPdf: 'Preview PDF',
    selectPaymentMode: 'Select Payment Mode',
    updatePaymentMode: 'Update Payment Mode',
    updating: 'Updating...',
    confirm: 'Confirm',
    invoicePdf: 'Invoice PDF',
    share: 'Share',
    download: 'Download',
    saving: 'Saving...',
    pdfNotReady: 'PDF is not ready yet.',
    pdfNotReadyShort: 'PDF is not ready.',
    failedToGeneratePdf: 'Failed to generate PDF.',
    failedToGeneratePdfRetry: 'Failed to generate PDF. Please try again.',
    savedTitle: 'Saved!',
    savedMessage: 'Invoice saved to Downloads folder.',
    failedToSavePdf: 'Failed to save PDF.',
    shareFailedTitle: 'Share Failed',
    shareFailedMessage: 'Unable to share the invoice PDF.',
    printFailedTitle: 'Print Failed',
    printFailedMessage: 'Unable to open the print dialog.',
    unableToOpenDialer: 'Unable to open dialer',
    paymentUpdated: 'Invoice marked as paid ',
    failedToUpdatePayment: 'Failed to update payment status ',
    couldNotRenderPdf: 'Could not render PDF preview.',
  },
};
