export default {
  common: {
    cancel: 'रद्द करें',
    delete: 'हटाएं',
    tryAgain: 'पुनः प्रयास करें',
    retrying: 'जाँच की जा रही है...',
    save: 'सहेजें',
    edit: 'संपादित करें',
    update: 'अपडेट करें',
    close: 'बंद करें',
    error: 'त्रुटि',
    success: 'सफलता',
    selectCustomer: 'ग्राहक चुनें',
    noCustomersFound: 'कोई ग्राहक नहीं मिला।',
    selectCustomerTitle: 'ग्राहक चुनें',
    cash: 'नकद',
    upi: 'UPI',
    card: 'कार्ड',
    netBanking: 'नेट बैंकिंग',
    paid: 'भुगतान किया गया',
    pending: 'लंबित',
    required: 'आवश्यक',
    deleteInvoiceTitle: 'इनवॉइस हटाएं',
    deleteInvoiceMessage: 'क्या आप वाकई इस इनवॉइस को हटाना चाहते हैं?',
    invoiceDeleted: 'इनवॉइस सफलतापूर्वक हटा दिया गया',
    failedDeleteInvoice: 'इनवॉइस हटाने में विफल',
  },

  network: {
    offlineTitle: 'इंटरनेट कनेक्शन नहीं है',
    offlineMessage:
      'कुछ सुविधाओं के लिए इंटरनेट कनेक्शन आवश्यक है। कृपया इंटरनेट से दोबारा कनेक्ट करें और फिर प्रयास करें।',
  },

  stepIndicator: {
    customer: 'ग्राहक',
    products: 'उत्पाद',
    summary: 'सारांश',
  },

  bottomNav: {
    home: 'होम',
    create: 'बनाएं',
    labour: 'श्रम',
    invoices: 'इनवॉइस',
  },

  splash: {
    companyLine1: 'आधी इंजन',
    companyLine2: 'सर्विसेज',
    tagline: 'ऑनलाइन बिलिंग सिस्टम',
    loadingTexts: [
      'सिस्टम शुरू हो रहा है...',
      'सेवाओं से कनेक्ट हो रहा है...',
      'मॉड्यूल लोड हो रहे हैं...',
      'डैशबोर्ड तैयार हो रहा है...',
      'लगभग तैयार...',
    ],
  },

  login: {
    companyName: 'आधी इंजन सर्विसेज',
    welcomeBack: 'वापसी पर स्वागत है',
    enterPin: 'जारी रखने के लिए अपना 4 अंकों का PIN दर्ज करें',
    somethingWrong: 'कुछ गलत हो गया',
    wrongPin: 'गलत PIN',
    onlineBillingSystem: 'ऑनलाइन बिलिंग सिस्टम',
    designedBy: 'Shanmugapriya Iyappan द्वारा डिज़ाइन और विकसित',
    deleteKey: 'हटाएं',
    keyLabel: 'कुंजी {{label}}',
  },

  settings: {
    title: 'सेटिंग्स',
    dataManagement: 'डेटा प्रबंधन',
    backupData: 'डेटा बैकअप',
    exportInvoices: 'इनवॉइस निर्यात करें (.JSON)',
    restoreBackup: 'बैकअप पुनर्स्थापित करें',
    systemMaintenance: 'सिस्टम रखरखाव',
    deleteAllReports: 'सभी रिपोर्ट हटाएं',
    logout: 'लॉग आउट',
    logoutConfirmTitle: 'क्या आप वाकई लॉग आउट करना चाहते हैं?',
    logoutConfirmMessage: 'आप सिस्टम से लॉग आउट हो जाएंगे।',
    footer: 'आधी इंजन सर्विस v1.0.0 (बिल्ड 2026)',
    language: 'भाषा',
    appLanguage: 'ऐप भाषा',
    english: 'अंग्रेज़ी',
    tamil: 'तमिल',
  },

  dashboard: {
    title: 'डैशबोर्ड',
    subtitle: 'आधी इंजन सर्विस',
    quickActions: 'त्वरित कार्य',
    productInvoice: 'उत्पाद इनवॉइस',
    labourInvoices: 'श्रम इनवॉइस',
    totalInvoices: 'कुल इनवॉइस',
    totalRevenue: 'कुल आय',
    customers: 'ग्राहक',
    monthlySummary: 'मासिक सारांश',
    performance: '{{month}} का प्रदर्शन',
    recentInvoices: 'हाल के इनवॉइस',
    viewAll: 'सभी देखें',
    noInvoicesYet: 'अभी तक कोई इनवॉइस नहीं',
    unknownCustomer: 'अज्ञात ग्राहक',
    changeThisMonth: 'इस महीने {{value}}%',
  },

  customerList: {
    title: 'ग्राहक',
    record: 'रिकॉर्ड',
    records: 'रिकॉर्ड',
    searchPlaceholder: 'नाम, मोबाइल या पता से खोजें',
    resultsFor: '"{{query}}" के लिए {{count}} {{resultWord}}',
    result: 'परिणाम',
    results: 'परिणाम',
    noResultsFound: 'कोई परिणाम नहीं मिला',
    noCustomersYet: 'अभी तक कोई ग्राहक नहीं',
    nothingMatched: '"{{query}}" से कुछ भी मेल नहीं खाता',
    tapToAdd: 'पहला ग्राहक जोड़ने के लिए + दबाएं',
    deleteCustomerTitle: 'ग्राहक हटाएं?',
    deleteCustomerMessage:
      '"{{name}}" को स्थायी रूप से हटा दिया जाएगा। इसे वापस नहीं किया जा सकता।',
  },

  createCustomer: {
    editTitle: 'ग्राहक संपादित करें',
    addTitle: 'ग्राहक जोड़ें',
    subtitle: 'आधी इंजन सर्विस',
    heading: 'ग्राहक विवरण',
    descriptionEdit: 'ग्राहक की जानकारी नीचे अपडेट करें',
    descriptionAdd: 'नया ग्राहक जोड़ने के लिए नीचे दिए गए विवरण भरें',
    customerName: 'ग्राहक का नाम',
    enterFullName: 'पूरा नाम दर्ज करें',
    mobileNumber: 'मोबाइल नंबर',
    optional: '(वैकल्पिक)',
    enter10Digit: '10 अंकों का नंबर दर्ज करें',
    address: 'पता',
    enterAddress: 'गली, शहर, राज्य... दर्ज करें',
    updating: 'अपडेट हो रहा है....',
    saving: 'सहेजा जा रहा है....',
    updateCustomer: 'ग्राहक अपडेट करें',
    saveCustomer: 'ग्राहक सहेजें',
    discardTitle: 'बदलाव छोड़ें?',
    discardMessage:
      'आपके बदलाव सहेजे नहीं जाएंगे। क्या आप बाहर निकलना चाहते हैं?',
    discard: 'छोड़ें',
    keepEditing: 'संपादन जारी रखें',
    deleteCustomerTitle: 'ग्राहक हटाएं?',
    deleteCustomerMessage:
      '"{{name}}" को स्थायी रूप से हटा दिया जाएगा। इसे वापस नहीं किया जा सकता।',
    nameRequired: 'ग्राहक का नाम आवश्यक है',
    mobileDigits: 'मोबाइल नंबर 10 अंकों का होना चाहिए',
    addressRequired: 'पता आवश्यक है',
  },

  invoiceForm: {
    editInvoice: 'इनवॉइस संपादित करें',
    createInvoice: 'इनवॉइस बनाएं',
    editLabourInvoice: 'श्रम इनवॉइस संपादित करें',
    createLabourInvoice: 'श्रम इनवॉइस बनाएं',
    customerName: 'ग्राहक का नाम',
    paymentReceived: 'भुगतान प्राप्त हुआ',
    paymentMode: 'भुगतान का तरीका',
    selectPaymentMode: 'भुगतान का तरीका चुनें',
    invoiceDate: 'इनवॉइस की तारीख',
    billNo: 'बिल नंबर',
    addProduct: 'उत्पाद जोड़ें',
    addItem: 'आइटम जोड़ें',
    productNamePlaceholder: 'उत्पाद का नाम',
    descriptionPlaceholder: 'विवरण',
    amountPlaceholder: 'राशि',
    qty: 'मात्रा',
    unitPrice: 'इकाई मूल्य',
    addProductBtn: '＋ उत्पाद जोड़ें',
    addItemBtn: '＋ आइटम जोड़ें',
    items: 'आइटम ({{count}})',
    save: 'सहेजें',
    grandTotal: 'कुल राशि',
    updateBill: 'बिल अपडेट करें',
    generateBill: 'बिल बनाएं',
    pleaseSelectCustomer: 'कृपया ग्राहक चुनें',
    addAtLeastOneProduct: 'कम से कम एक उत्पाद जोड़ें',
    addAtLeastOneItem: 'कम से कम एक आइटम जोड़ें',
    invoiceUpdated: 'इनवॉइस सफलतापूर्वक अपडेट किया गया',
    invoiceCreated: 'इनवॉइस बनाया गया',
    labourInvoiceUpdated: 'श्रम इनवॉइस सफलतापूर्वक अपडेट किया गया',
    labourInvoiceCreated: 'श्रम इनवॉइस बनाया गया',
  },

  invoiceList: {
    billNoPrefix: 'बिल नंबर :{{no}}',
    total: 'कुल',
    unknownCustomer: 'अज्ञात ग्राहक',
    items: 'आइटम',
    itemCount: '{{count}} {{itemWord}}',
    item: 'आइटम',
    itemsWord: 'आइटम',
    tapToView: 'इनवॉइस विवरण देखने के लिए दबाएं',
    noInvoicesFound: 'कोई इनवॉइस नहीं मिला',
    createFirst: 'शुरू करने के लिए अपना पहला इनवॉइस बनाएं।',
    adjustFilters: 'फ़िल्टर या खोज क्वेरी को बदलकर देखें।',
    clearAllFilters: 'सभी फ़िल्टर साफ़ करें',
    searchPlaceholder: 'कोड, ग्राहक या मोबाइल से खोजें...',
    filters: 'फ़िल्टर',
    paymentStatus: 'भुगतान स्थिति',
    invoiceType: 'इनवॉइस प्रकार',
    dateRange: 'तारीख सीमा',
    clearAll: 'सभी साफ़ करें',
    applyFilters: 'फ़िल्टर लागू करें',
    all: 'सभी',
    product: 'उत्पाद',
    labour: 'श्रम',
  },

  invoicePreview: {
    title: 'इनवॉइस पूर्वावलोकन',
    companySubtitle: 'आधी इंजन केयर',
    billNo: 'बिल नंबर:',
    date: 'तारीख:',
    customerDetails: 'ग्राहक विवरण',
    to: 'प्रति',
    noPhoneAvailable: 'कोई फोन नंबर उपलब्ध नहीं',
    paymentMode: 'भुगतान का तरीका',
    sNo: 'क्र.सं.',
    descriptionCol: 'विवरण',
    qty: 'मात्रा',
    rate: 'दर',
    amount: 'राशि',
    total: 'कुल',
    amountInWords: 'राशि शब्दों में',
    sign: 'हस्ताक्षर',
    markAsPaid: 'भुगतान किया गया के रूप में चिह्नित करें',
    generatingPdf: 'PDF तैयार हो रही है...',
    previewPdf: 'PDF पूर्वावलोकन',
    selectPaymentMode: 'भुगतान का तरीका चुनें',
    updatePaymentMode: 'भुगतान का तरीका अपडेट करें',
    updating: 'अपडेट हो रहा है...',
    confirm: 'पुष्टि करें',
    invoicePdf: 'इनवॉइस PDF',
    share: 'साझा करें',
    download: 'डाउनलोड करें',
    saving: 'सहेजा जा रहा है...',
    pdfNotReady: 'PDF अभी तैयार नहीं है।',
    pdfNotReadyShort: 'PDF तैयार नहीं है।',
    failedToGeneratePdf: 'PDF तैयार करने में विफल।',
    failedToGeneratePdfRetry:
      'PDF तैयार करने में विफल। कृपया पुनः प्रयास करें।',
    savedTitle: 'सहेजा गया!',
    savedMessage: 'इनवॉइस Downloads फ़ोल्डर में सहेजा गया।',
    failedToSavePdf: 'PDF सहेजने में विफल।',
    shareFailedTitle: 'साझा करना विफल',
    shareFailedMessage: 'इनवॉइस PDF साझा नहीं की जा सकी।',
    printFailedTitle: 'प्रिंट विफल',
    printFailedMessage: 'प्रिंट डायलॉग खोलने में असमर्थ।',
    unableToOpenDialer: 'डायलर खोलने में असमर्थ',
    paymentUpdated: 'इनवॉइस को भुगतान किया गया के रूप में चिह्नित किया गया',
    failedToUpdatePayment: 'भुगतान स्थिति अपडेट करने में विफल',
    couldNotRenderPdf: 'PDF पूर्वावलोकन प्रदर्शित नहीं किया जा सका।',
  },
  notifications: {
    sectionTitle: 'सूचनाएं',
    paymentReminders: 'सूचनाएं',
    paymentRemindersDescription:
      'भुगतान रिमाइंडर, साप्ताहिक सारांश और इनवॉइस अपडेट पाएं।',
    permissionTitle: 'सूचनाएं बंद हैं',
    permissionMessage:
      'भुगतान रिमाइंडर पाने के लिए डिवाइस सेटिंग में सूचनाओं की अनुमति दें।',
    setupFailed: 'भुगतान रिमाइंडर सेट नहीं हो सके। कृपया फिर से प्रयास करें।',
    channelName: 'भुगतान रिमाइंडर',
    unknownCustomer: 'आपके ग्राहक',
    pendingTitle: 'भुगतान अभी बाकी है',
    pendingMessage:
      '{{customer}} के बिल #{{billNo}} ({{amount}}) का भुगतान {{days}} दिन बाद भी बाकी है।',
    weeklyTitle: 'लंबित भुगतानों का साप्ताहिक सारांश',
    weeklyMessage:
      '{{count}} बिलों का कुल {{amount}} भुगतान अभी लंबित है।',
    invoiceCreatedTitle: 'नया बिल बनाया गया',
    invoiceCreatedMessage:
      '{{customer}} के लिए {{amount}} का बिल #{{billNo}} सेव हो गया है।',
    paymentReceivedTitle: 'भुगतान प्राप्त हुआ',
    paymentReceivedMessage:
      '{{customer}} के बिल #{{billNo}} के लिए {{amount}} का भुगतान प्राप्त हुआ।',
  },
};
