export default {
  common: {
    cancel: 'ರದ್ದುಮಾಡಿ',
    delete: 'ಅಳಿಸಿ',
    tryAgain: 'ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ',
    retrying: 'ಪರಿಶೀಲಿಸಲಾಗುತ್ತಿದೆ...',
    save: 'ಉಳಿಸಿ',
    edit: 'ತಿದ್ದು',
    update: 'ನವೀಕರಿಸಿ',
    close: 'ಮುಚ್ಚಿ',
    error: 'ದೋಷ',
    success: 'ಯಶಸ್ಸು',
    selectCustomer: 'ಗ್ರಾಹಕರನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    noCustomersFound: 'ಯಾವುದೇ ಗ್ರಾಹಕರು ಕಂಡುಬಂದಿಲ್ಲ.',
    selectCustomerTitle: 'ಗ್ರಾಹಕರನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    cash: 'ನಗದು',
    upi: 'UPI',
    card: 'ಕಾರ್ಡ್',
    netBanking: 'ನೆಟ್ ಬ್ಯಾಂಕಿಂಗ್',
    paid: 'ಪಾವತಿಸಲಾಗಿದೆ',
    pending: 'ಬಾಕಿಯಿದೆ',
    required: 'ಅಗತ್ಯವಿದೆ',
    deleteInvoiceTitle: 'ಇನ್‌ವಾಯ್ಸ್ ಅಳಿಸಿ',
    deleteInvoiceMessage: 'ಈ ಇನ್‌ವಾಯ್ಸ್ ಅನ್ನು ಅಳಿಸಲು ನೀವು ಖಚಿತವಾಗಿ ಬಯಸುವಿರಾ?',
    invoiceDeleted: 'ಇನ್‌ವಾಯ್ಸ್ ಯಶಸ್ವಿಯಾಗಿ ಅಳಿಸಲಾಗಿದೆ',
    failedDeleteInvoice: 'ಇನ್‌ವಾಯ್ಸ್ ಅಳಿಸಲು ವಿಫಲವಾಗಿದೆ',
  },

  network: {
    offlineTitle: 'ಇಂಟರ್ನೆಟ್ ಸಂಪರ್ಕ ಇಲ್ಲ',
    offlineMessage:
      'ಕೆಲವು ವೈಶಿಷ್ಟ್ಯಗಳಿಗೆ ಇಂಟರ್ನೆಟ್ ಸಂಪರ್ಕ ಅಗತ್ಯವಿದೆ. ದಯವಿಟ್ಟು ಇಂಟರ್ನೆಟ್‌ಗೆ ಮರುಸಂಪರ್ಕಿಸಿ ಮತ್ತು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
  },
  stepIndicator: {
    customer: 'ಗ್ರಾಹಕರು',
    products: 'ಉತ್ಪನ್ನಗಳು',
    summary: 'ಸಾರಾಂಶ',
  },
  bottomNav: {
    home: 'ಮುಖಪುಟ',
    create: 'ರಚಿಸಿ',
    labour: 'ಕಾರ್ಮಿಕ',
    invoices: 'ಇನ್‌ವಾಯ್ಸ್‌ಗಳು',
  },
  splash: {
    companyLine1: 'ಆಧಿ ಎಂಜಿನ್',
    companyLine2: 'ಸರ್ವಿಸಸ್',
    tagline: 'ಆನ್‌ಲೈನ್ ಬಿಲ್ಲಿಂಗ್ ಸಿಸ್ಟಮ್',
    loadingTexts: [
      'ಸಿಸ್ಟಮ್ ಪ್ರಾರಂಭಿಸಲಾಗುತ್ತಿದೆ...',
      'ಸೇವೆಗಳೊಂದಿಗೆ ಸಂಪರ್ಕಿಸಲಾಗುತ್ತಿದೆ...',
      'ಮಾಡ್ಯೂಲ್‌ಗಳನ್ನು ಲೋಡ್ ಮಾಡಲಾಗುತ್ತಿದೆ...',
      'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್ ಸಿದ್ಧಪಡಿಸಲಾಗುತ್ತಿದೆ...',
      'ಬಹುತೇಕ ಸಿದ್ಧವಾಗಿದೆ...',
    ],
  },
  login: {
    companyName: 'ಆಧಿ ಎಂಜಿನ್ ಸರ್ವಿಸಸ್',
    welcomeBack: 'ಮತ್ತೆ ಸ್ವಾಗತ',
    enterPin: 'ಮುಂದುವರಿಸಲು ನಿಮ್ಮ 4 ಅಂಕಿಯ PIN ನಮೂದಿಸಿ',
    somethingWrong: 'ಏನೋ ತಪ್ಪಾಗಿದೆ',
    wrongPin: 'ತಪ್ಪಾದ PIN',
    onlineBillingSystem: 'ಆನ್‌ಲೈನ್ ಬಿಲ್ಲಿಂಗ್ ಸಿಸ್ಟಮ್',
    designedBy: 'Shanmugapriya Iyappan ವಿನ್ಯಾಸಗೊಳಿಸಿ ಅಭಿವೃದ್ಧಿಪಡಿಸಿದ್ದಾರೆ',
    deleteKey: 'ಅಳಿಸಿ',
    keyLabel: 'ಕೀ {{label}}',
  },
  settings: {
    title: 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    dataManagement: 'ಡೇಟಾ ನಿರ್ವಹಣೆ',
    backupData: 'ಡೇಟಾ ಬ್ಯಾಕಪ್',
    exportInvoices: 'ಇನ್‌ವಾಯ್ಸ್‌ಗಳನ್ನು ರಫ್ತು ಮಾಡಿ (.JSON)',
    restoreBackup: 'ಬ್ಯಾಕಪ್ ಮರುಸ್ಥಾಪಿಸಿ',
    systemMaintenance: 'ಸಿಸ್ಟಮ್ ನಿರ್ವಹಣೆ',
    deleteAllReports: 'ಎಲ್ಲಾ ವರದಿಗಳನ್ನು ಅಳಿಸಿ',
    logout: 'ಲಾಗ್ ಔಟ್',
    logoutConfirmTitle: 'ನೀವು ಖಚಿತವಾಗಿ ಲಾಗ್ ಔಟ್ ಮಾಡಲು ಬಯಸುವಿರಾ?',
    logoutConfirmMessage: 'ನೀವು ಸಿಸ್ಟಮ್‌ನಿಂದ ಲಾಗ್ ಔಟ್ ಆಗುತ್ತೀರಿ.',
    footer: 'ಆಧಿ ಎಂಜಿನ್ ಸರ್ವಿಸ್ v1.0.0 (ಬಿಲ್ಡ್ 2026)',
    language: 'ಭಾಷೆ',
    appLanguage: 'ಆಪ್ ಭಾಷೆ',
    english: 'ಇಂಗ್ಲಿಷ್',
    tamil: 'ತಮಿಳು',
  },
  dashboard: {
    title: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    subtitle: 'ಆಧಿ ಎಂಜಿನ್ ಸರ್ವಿಸ್',
    quickActions: 'ತ್ವರಿತ ಕಾರ್ಯಗಳು',
    productInvoice: 'ಉತ್ಪನ್ನ ಇನ್‌ವಾಯ್ಸ್',
    labourInvoices: 'ಕಾರ್ಮಿಕ ಇನ್‌ವಾಯ್ಸ್‌ಗಳು',
    totalInvoices: 'ಒಟ್ಟು ಇನ್‌ವಾಯ್ಸ್‌ಗಳು',
    totalRevenue: 'ಒಟ್ಟು ಆದಾಯ',
    customers: 'ಗ್ರಾಹಕರು',
    monthlySummary: 'ಮಾಸಿಕ ಸಾರಾಂಶ',
    performance: '{{month}} ಕಾರ್ಯಕ್ಷಮತೆ',
    recentInvoices: 'ಇತ್ತೀಚಿನ ಇನ್‌ವಾಯ್ಸ್‌ಗಳು',
    viewAll: 'ಎಲ್ಲವನ್ನೂ ನೋಡಿ',
    noInvoicesYet: 'ಇನ್ನೂ ಯಾವುದೇ ಇನ್‌ವಾಯ್ಸ್‌ಗಳಿಲ್ಲ',
    unknownCustomer: 'ಅಜ್ಞಾತ ಗ್ರಾಹಕ',
    changeThisMonth: 'ಈ ತಿಂಗಳು {{value}}%',
  },
  customerList: {
    title: 'ಗ್ರಾಹಕರು',
    record: 'ದಾಖಲೆ',
    records: 'ದಾಖಲೆಗಳು',
    searchPlaceholder: 'ಹೆಸರು, ಮೊಬೈಲ್ ಅಥವಾ ವಿಳಾಸದಿಂದ ಹುಡುಕಿ',
    resultsFor: '"{{query}}" ಗಾಗಿ {{count}} {{resultWord}}',
    result: 'ಫಲಿತಾಂಶ',
    results: 'ಫಲಿತಾಂಶಗಳು',
    noResultsFound: 'ಯಾವುದೇ ಫಲಿತಾಂಶಗಳು ಕಂಡುಬಂದಿಲ್ಲ',
    noCustomersYet: 'ಇನ್ನೂ ಯಾವುದೇ ಗ್ರಾಹಕರಿಲ್ಲ',
    nothingMatched: '"{{query}}" ಗೆ ಯಾವುದೂ ಹೊಂದಿಕೆಯಾಗಿಲ್ಲ',
    tapToAdd: 'ನಿಮ್ಮ ಮೊದಲ ಗ್ರಾಹಕರನ್ನು ಸೇರಿಸಲು + ಒತ್ತಿರಿ',
    deleteCustomerTitle: 'ಗ್ರಾಹಕರನ್ನು ಅಳಿಸಬೇಕೇ?',
    deleteCustomerMessage:
      '"{{name}}" ಅನ್ನು ಶಾಶ್ವತವಾಗಿ ತೆಗೆದುಹಾಕಲಾಗುತ್ತದೆ. ಇದನ್ನು ಹಿಂತಿರುಗಿಸಲು ಸಾಧ್ಯವಿಲ್ಲ.',
  },
  createCustomer: {
    editTitle: 'ಗ್ರಾಹಕರನ್ನು ತಿದ್ದು',
    addTitle: 'ಗ್ರಾಹಕರನ್ನು ಸೇರಿಸಿ',
    subtitle: 'ಆಧಿ ಎಂಜಿನ್ ಸರ್ವಿಸ್',
    heading: 'ಗ್ರಾಹಕರ ವಿವರಗಳು',
    descriptionEdit: 'ಕೆಳಗಿನ ಗ್ರಾಹಕರ ಮಾಹಿತಿಯನ್ನು ನವೀಕರಿಸಿ',
    descriptionAdd: 'ಹೊಸ ಗ್ರಾಹಕರನ್ನು ಸೇರಿಸಲು ಕೆಳಗಿನ ವಿವರಗಳನ್ನು ಭರ್ತಿ ಮಾಡಿ',
    customerName: 'ಗ್ರಾಹಕರ ಹೆಸರು',
    enterFullName: 'ಪೂರ್ಣ ಹೆಸರನ್ನು ನಮೂದಿಸಿ',
    mobileNumber: 'ಮೊಬೈಲ್ ಸಂಖ್ಯೆ',
    optional: '(ಐಚ್ಛಿಕ)',
    enter10Digit: '10 ಅಂಕಿಯ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ',
    address: 'ವಿಳಾಸ',
    enterAddress: 'ರಸ್ತೆ, ನಗರ, ರಾಜ್ಯ... ನಮೂದಿಸಿ',
    updating: 'ನವೀಕರಿಸಲಾಗುತ್ತಿದೆ....',
    saving: 'ಉಳಿಸಲಾಗುತ್ತಿದೆ....',
    updateCustomer: 'ಗ್ರಾಹಕರನ್ನು ನವೀಕರಿಸಿ',
    saveCustomer: 'ಗ್ರಾಹಕರನ್ನು ಉಳಿಸಿ',
    discardTitle: 'ಬದಲಾವಣೆಗಳನ್ನು ತ್ಯಜಿಸಬೇಕೇ?',
    discardMessage:
      'ನಿಮ್ಮ ಬದಲಾವಣೆಗಳನ್ನು ಉಳಿಸಲಾಗುವುದಿಲ್ಲ. ನೀವು ಹೊರಹೋಗಲು ಬಯಸುವಿರಾ?',
    discard: 'ತ್ಯಜಿಸಿ',
    keepEditing: 'ತಿದ್ದುಪಡಿ ಮುಂದುವರಿಸಿ',
    deleteCustomerTitle: 'ಗ್ರಾಹಕರನ್ನು ಅಳಿಸಬೇಕೇ?',
    deleteCustomerMessage:
      '"{{name}}" ಅನ್ನು ಶಾಶ್ವತವಾಗಿ ತೆಗೆದುಹಾಕಲಾಗುತ್ತದೆ. ಇದನ್ನು ಹಿಂತಿರುಗಿಸಲು ಸಾಧ್ಯವಿಲ್ಲ.',
    nameRequired: 'ಗ್ರಾಹಕರ ಹೆಸರು ಅಗತ್ಯವಿದೆ',
    mobileDigits: 'ಮೊಬೈಲ್ ಸಂಖ್ಯೆ 10 ಅಂಕಿಗಳಾಗಿರಬೇಕು',
    addressRequired: 'ವಿಳಾಸ ಅಗತ್ಯವಿದೆ',
  },
  invoiceForm: {
    editInvoice: 'ಇನ್‌ವಾಯ್ಸ್ ತಿದ್ದು',
    createInvoice: 'ಇನ್‌ವಾಯ್ಸ್ ರಚಿಸಿ',
    editLabourInvoice: 'ಕಾರ್ಮಿಕ ಇನ್‌ವಾಯ್ಸ್ ತಿದ್ದು',
    createLabourInvoice: 'ಕಾರ್ಮಿಕ ಇನ್‌ವಾಯ್ಸ್ ರಚಿಸಿ',
    customerName: 'ಗ್ರಾಹಕರ ಹೆಸರು',
    paymentReceived: 'ಪಾವತಿ ಸ್ವೀಕರಿಸಲಾಗಿದೆ',
    paymentMode: 'ಪಾವತಿ ವಿಧಾನ',
    selectPaymentMode: 'ಪಾವತಿ ವಿಧಾನವನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    invoiceDate: 'ಇನ್‌ವಾಯ್ಸ್ ದಿನಾಂಕ',
    billNo: 'ಬಿಲ್ ಸಂಖ್ಯೆ',
    addProduct: 'ಉತ್ಪನ್ನ ಸೇರಿಸಿ',
    addItem: 'ಐಟಂ ಸೇರಿಸಿ',
    productNamePlaceholder: 'ಉತ್ಪನ್ನದ ಹೆಸರು',
    descriptionPlaceholder: 'ವಿವರಣೆ',
    amountPlaceholder: 'ಮೊತ್ತ',
    qty: 'ಪ್ರಮಾಣ',
    unitPrice: 'ಘಟಕ ಬೆಲೆ',
    addProductBtn: '＋ ಉತ್ಪನ್ನ ಸೇರಿಸಿ',
    addItemBtn: '＋ ಐಟಂ ಸೇರಿಸಿ',
    items: 'ಐಟಂಗಳು ({{count}})',
    save: 'ಉಳಿಸಿ',
    grandTotal: 'ಒಟ್ಟು ಮೊತ್ತ',
    updateBill: 'ಬಿಲ್ ನವೀಕರಿಸಿ',
    generateBill: 'ಬಿಲ್ ರಚಿಸಿ',
    pleaseSelectCustomer: 'ದಯವಿಟ್ಟು ಗ್ರಾಹಕರನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    addAtLeastOneProduct: 'ಕನಿಷ್ಠ ಒಂದು ಉತ್ಪನ್ನವನ್ನು ಸೇರಿಸಿ',
    addAtLeastOneItem: 'ಕನಿಷ್ಠ ಒಂದು ಐಟಂ ಅನ್ನು ಸೇರಿಸಿ',
    invoiceUpdated: 'ಇನ್‌ವಾಯ್ಸ್ ಯಶಸ್ವಿಯಾಗಿ ನವೀಕರಿಸಲಾಗಿದೆ',
    invoiceCreated: 'ಇನ್‌ವಾಯ್ಸ್ ರಚಿಸಲಾಗಿದೆ',
    labourInvoiceUpdated: 'ಕಾರ್ಮಿಕ ಇನ್‌ವಾಯ್ಸ್ ಯಶಸ್ವಿಯಾಗಿ ನವೀಕರಿಸಲಾಗಿದೆ',
    labourInvoiceCreated: 'ಕಾರ್ಮಿಕ ಇನ್‌ವಾಯ್ಸ್ ರಚಿಸಲಾಗಿದೆ',
  },
  invoiceList: {
    billNoPrefix: 'ಬಿಲ್ ಸಂಖ್ಯೆ :{{no}}',
    total: 'ಒಟ್ಟು',
    unknownCustomer: 'ಅಜ್ಞಾತ ಗ್ರಾಹಕ',
    items: 'ಐಟಂಗಳು',
    itemCount: '{{count}} {{itemWord}}',
    item: 'ಐಟಂ',
    itemsWord: 'ಐಟಂಗಳು',
    tapToView: 'ಇನ್‌ವಾಯ್ಸ್ ವಿವರಗಳನ್ನು ನೋಡಲು ಒತ್ತಿರಿ',
    noInvoicesFound: 'ಯಾವುದೇ ಇನ್‌ವಾಯ್ಸ್‌ಗಳು ಕಂಡುಬಂದಿಲ್ಲ',
    createFirst: 'ಪ್ರಾರಂಭಿಸಲು ನಿಮ್ಮ ಮೊದಲ ಇನ್‌ವಾಯ್ಸ್ ರಚಿಸಿ.',
    adjustFilters: 'ಫಿಲ್ಟರ್‌ಗಳು ಅಥವಾ ಹುಡುಕಾಟವನ್ನು ಬದಲಾಯಿಸಿ ಪ್ರಯತ್ನಿಸಿ.',
    clearAllFilters: 'ಎಲ್ಲಾ ಫಿಲ್ಟರ್‌ಗಳನ್ನು ತೆರವುಗೊಳಿಸಿ',
    searchPlaceholder: 'ಕೋಡ್, ಗ್ರಾಹಕ ಅಥವಾ ಮೊಬೈಲ್ ಮೂಲಕ ಹುಡುಕಿ...',
    filters: 'ಫಿಲ್ಟರ್‌ಗಳು',
    paymentStatus: 'ಪಾವತಿ ಸ್ಥಿತಿ',
    invoiceType: 'ಇನ್‌ವಾಯ್ಸ್ ಪ್ರಕಾರ',
    dateRange: 'ದಿನಾಂಕ ವ್ಯಾಪ್ತಿ',
    clearAll: 'ಎಲ್ಲವನ್ನೂ ತೆರವುಗೊಳಿಸಿ',
    applyFilters: 'ಫಿಲ್ಟರ್‌ಗಳನ್ನು ಅನ್ವಯಿಸಿ',
    all: 'ಎಲ್ಲಾ',
    product: 'ಉತ್ಪನ್ನ',
    labour: 'ಕಾರ್ಮಿಕ',
  },
  invoicePreview: {
    title: 'ಇನ್‌ವಾಯ್ಸ್ ಪೂರ್ವವೀಕ್ಷಣೆ',
    companySubtitle: 'ಆಧಿ ಎಂಜಿನ್ ಕೇರ್',
    billNo: 'ಬಿಲ್ ಸಂಖ್ಯೆ:',
    date: 'ದಿನಾಂಕ:',
    customerDetails: 'ಗ್ರಾಹಕರ ವಿವರಗಳು',
    to: 'ಗೆ',
    noPhoneAvailable: 'ಫೋನ್ ಸಂಖ್ಯೆ ಲಭ್ಯವಿಲ್ಲ',
    paymentMode: 'ಪಾವತಿ ವಿಧಾನ',
    sNo: 'ಕ್ರಮ ಸಂಖ್ಯೆ',
    descriptionCol: 'ವಿವರಣೆ',
    qty: 'ಪ್ರಮಾಣ',
    rate: 'ದರ',
    amount: 'ಮೊತ್ತ',
    total: 'ಒಟ್ಟು',
    amountInWords: 'ಮೊತ್ತವನ್ನು ಪದಗಳಲ್ಲಿ',
    sign: 'ಸಹಿ',
    markAsPaid: 'ಪಾವತಿಸಲಾಗಿದೆ ಎಂದು ಗುರುತಿಸಿ',
    generatingPdf: 'PDF ರಚಿಸಲಾಗುತ್ತಿದೆ...',
    previewPdf: 'PDF ಪೂರ್ವವೀಕ್ಷಣೆ',
    selectPaymentMode: 'ಪಾವತಿ ವಿಧಾನವನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    updatePaymentMode: 'ಪಾವತಿ ವಿಧಾನವನ್ನು ನವೀಕರಿಸಿ',
    updating: 'ನವೀಕರಿಸಲಾಗುತ್ತಿದೆ...',
    confirm: 'ದೃಢೀಕರಿಸಿ',
    invoicePdf: 'ಇನ್‌ವಾಯ್ಸ್ PDF',
    share: 'ಹಂಚಿಕೊಳ್ಳಿ',
    download: 'ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ',
    saving: 'ಉಳಿಸಲಾಗುತ್ತಿದೆ...',
    pdfNotReady: 'PDF ಇನ್ನೂ ಸಿದ್ಧವಾಗಿಲ್ಲ.',
    pdfNotReadyShort: 'PDF ಸಿದ್ಧವಾಗಿಲ್ಲ.',
    failedToGeneratePdf: 'PDF ರಚಿಸಲು ವಿಫಲವಾಗಿದೆ.',
    failedToGeneratePdfRetry:
      'PDF ರಚಿಸಲು ವಿಫಲವಾಗಿದೆ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
    savedTitle: 'ಉಳಿಸಲಾಗಿದೆ!',
    savedMessage: 'ಇನ್‌ವಾಯ್ಸ್ ಅನ್ನು Downloads ಫೋಲ್ಡರ್‌ನಲ್ಲಿ ಉಳಿಸಲಾಗಿದೆ.',
    failedToSavePdf: 'PDF ಉಳಿಸಲು ವಿಫಲವಾಗಿದೆ.',
    shareFailedTitle: 'ಹಂಚಿಕೊಳ್ಳಲು ವಿಫಲವಾಗಿದೆ',
    shareFailedMessage: 'ಇನ್‌ವಾಯ್ಸ್ PDF ಹಂಚಿಕೊಳ್ಳಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ.',
    printFailedTitle: 'ಪ್ರಿಂಟ್ ವಿಫಲವಾಗಿದೆ',
    printFailedMessage: 'ಪ್ರಿಂಟ್ ಡೈಲಾಗ್ ತೆರೆಯಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ.',
    unableToOpenDialer: 'ಡಯಲರ್ ತೆರೆಯಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ',
    paymentUpdated: 'ಇನ್‌ವಾಯ್ಸ್ ಅನ್ನು ಪಾವತಿಸಲಾಗಿದೆ ಎಂದು ಗುರುತಿಸಲಾಗಿದೆ',
    failedToUpdatePayment: 'ಪಾವತಿ ಸ್ಥಿತಿಯನ್ನು ನವೀಕರಿಸಲು ವಿಫಲವಾಗಿದೆ',
    couldNotRenderPdf: 'PDF ಪೂರ್ವವೀಕ್ಷಣೆಯನ್ನು ಪ್ರದರ್ಶಿಸಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ.',
  },
  notifications: {
    sectionTitle: 'ಅಧಿಸೂಚನೆಗಳು',
    paymentReminders: 'ಅಧಿಸೂಚನೆಗಳು',
    paymentRemindersDescription:
      'ಪಾವತಿ ಜ್ಞಾಪನೆಗಳು, ವಾರದ ಸಾರಾಂಶ ಮತ್ತು ಇನ್‌ವಾಯ್ಸ್ ನವೀಕರಣಗಳನ್ನು ಪಡೆಯಿರಿ.',
    permissionTitle: 'ಅಧಿಸೂಚನೆಗಳು ಆಫ್ ಆಗಿವೆ',
    permissionMessage:
      'ಪಾವತಿ ಜ್ಞಾಪನೆಗಳನ್ನು ಪಡೆಯಲು ನಿಮ್ಮ ಸಾಧನದ ಸೆಟ್ಟಿಂಗ್‌ಗಳಲ್ಲಿ ಅಧಿಸೂಚನೆಗಳನ್ನು ಅನುಮತಿಸಿ.',
    setupFailed: 'ಪಾವತಿ ಜ್ಞಾಪನೆಗಳನ್ನು ಹೊಂದಿಸಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
    channelName: 'ಪಾವತಿ ಜ್ಞಾಪನೆಗಳು',
    unknownCustomer: 'ನಿಮ್ಮ ಗ್ರಾಹಕರು',
    pendingTitle: 'ಪಾವತಿ ಇನ್ನೂ ಬಾಕಿಯಿದೆ',
    pendingMessage:
      '{{customer}} ಅವರ ಬಿಲ್ #{{billNo}} ({{amount}}) ರ ಪಾವತಿ {{days}} ದಿನಗಳಾದರೂ ಬಾಕಿಯಿದೆ.',
    weeklyTitle: 'ವಾರದ ಬಾಕಿ ಪಾವತಿಗಳ ಸಾರಾಂಶ',
    weeklyMessage: '{{count}} ಬಿಲ್‌ಗಳಿಗೆ ಒಟ್ಟು {{amount}} ಪಾವತಿ ಬಾಕಿಯಿದೆ.',
    invoiceCreatedTitle: 'ಹೊಸ ಬಿಲ್ ರಚಿಸಲಾಗಿದೆ',
    invoiceCreatedMessage:
      '{{customer}} ಅವರ {{amount}} ಮೊತ್ತದ ಬಿಲ್ #{{billNo}} ಉಳಿಸಲಾಗಿದೆ.',
    paymentReceivedTitle: 'ಪಾವತಿ ಸ್ವೀಕರಿಸಲಾಗಿದೆ',
    paymentReceivedMessage:
      '{{customer}} ಅವರ ಬಿಲ್ #{{billNo}} ಗೆ {{amount}} ಪಾವತಿಯನ್ನು ಸ್ವೀಕರಿಸಲಾಗಿದೆ.',
  },
};
