export default {
  common: {
    cancel: 'റദ്ദാക്കുക',
    delete: 'ഇല്ലാതാക്കുക',
    tryAgain: 'വീണ്ടും ശ്രമിക്കുക',
    retrying: 'പരിശോധിക്കുന്നു...',
    save: 'സേവ് ചെയ്യുക',
    edit: 'എഡിറ്റ് ചെയ്യുക',
    update: 'അപ്‌ഡേറ്റ് ചെയ്യുക',
    close: 'അടയ്ക്കുക',
    error: 'പിശക്',
    success: 'വിജയം',
    selectCustomer: 'ഉപഭോക്താവിനെ തിരഞ്ഞെടുക്കുക',
    noCustomersFound: 'ഉപഭോക്താക്കളെ കണ്ടെത്തിയില്ല.',
    selectCustomerTitle: 'ഉപഭോക്താവിനെ തിരഞ്ഞെടുക്കുക',
    cash: 'പണം',
    upi: 'UPI',
    card: 'കാർഡ്',
    netBanking: 'നെറ്റ് ബാങ്കിംഗ്',
    paid: 'അടച്ചു',
    pending: 'തീർപ്പാക്കാത്തത്',
    required: 'ആവശ്യമാണ്',
    deleteInvoiceTitle: 'ഇൻവോയ്സ് ഇല്ലാതാക്കുക',
    deleteInvoiceMessage: 'ഈ ഇൻവോയ്സ് ഇല്ലാതാക്കണമെന്ന് ഉറപ്പാണോ?',
    invoiceDeleted: 'ഇൻവോയ്സ് വിജയകരമായി ഇല്ലാതാക്കി',
    failedDeleteInvoice: 'ഇൻവോയ്സ് ഇല്ലാതാക്കാൻ കഴിഞ്ഞില്ല',
  },
  network: {
    offlineTitle: 'ഇന്റർനെറ്റ് കണക്ഷൻ ഇല്ല',
    offlineMessage:
      'ചില ഫീച്ചറുകൾക്ക് ഇന്റർനെറ്റ് കണക്ഷൻ ആവശ്യമാണ്. ദയവായി ഇന്റർനെറ്റിലേക്ക് വീണ്ടും കണക്റ്റ് ചെയ്ത് ശ്രമിക്കുക.',
  },
  stepIndicator: {
    customer: 'ഉപഭോക്താവ്',
    products: 'ഉൽപ്പന്നങ്ങൾ',
    summary: 'സംഗ്രഹം',
  },
  bottomNav: {
    home: 'ഹോം',
    create: 'സൃഷ്ടിക്കുക',
    labour: 'തൊഴിൽ',
    invoices: 'ഇൻവോയ്സുകൾ',
  },
  splash: {
    companyLine1: 'ആധി എഞ്ചിൻ',
    companyLine2: 'സർവീസസ്',
    tagline: 'ഓൺലൈൻ ബില്ലിംഗ് സിസ്റ്റം',
    loadingTexts: [
      'സിസ്റ്റം ആരംഭിക്കുന്നു...',
      'സേവനങ്ങളുമായി ബന്ധിപ്പിക്കുന്നു...',
      'മൊഡ്യൂളുകൾ ലോഡ് ചെയ്യുന്നു...',
      'ഡാഷ്ബോർഡ് തയ്യാറാക്കുന്നു...',
      'ഏകദേശം തയ്യാറായി...',
    ],
  },
  login: {
    companyName: 'ആധി എഞ്ചിൻ സർവീസസ്',
    welcomeBack: 'വീണ്ടും സ്വാഗതം',
    enterPin: 'തുടരാൻ നിങ്ങളുടെ 4 അക്ക PIN നൽകുക',
    somethingWrong: 'എന്തോ തെറ്റ് സംഭവിച്ചു',
    wrongPin: 'തെറ്റായ PIN',
    onlineBillingSystem: 'ഓൺലൈൻ ബില്ലിംഗ് സിസ്റ്റം',
    designedBy: 'Shanmugapriya Iyappan രൂപകൽപ്പന ചെയ്ത് വികസിപ്പിച്ചത്',
    deleteKey: 'ഇല്ലാതാക്കുക',
    keyLabel: 'കീ {{label}}',
  },
  settings: {
    title: 'ക്രമീകരണങ്ങൾ',
    dataManagement: 'ഡാറ്റ മാനേജ്മെന്റ്',
    backupData: 'ഡാറ്റ ബാക്കപ്പ്',
    exportInvoices: 'ഇൻവോയ്സുകൾ എക്സ്പോർട്ട് ചെയ്യുക (.JSON)',
    restoreBackup: 'ബാക്കപ്പ് പുനഃസ്ഥാപിക്കുക',
    systemMaintenance: 'സിസ്റ്റം പരിപാലനം',
    deleteAllReports: 'എല്ലാ റിപ്പോർട്ടുകളും ഇല്ലാതാക്കുക',
    logout: 'ലോഗ് ഔട്ട്',
    logoutConfirmTitle: 'നിങ്ങൾക്ക് ലോഗ് ഔട്ട് ചെയ്യണമെന്ന് ഉറപ്പാണോ?',
    logoutConfirmMessage: 'നിങ്ങൾ സിസ്റ്റത്തിൽ നിന്ന് ലോഗ് ഔട്ട് ചെയ്യപ്പെടും.',
    footer: 'ആധി എഞ്ചിൻ സർവീസ് v1.0.0 (ബിൽഡ് 2026)',
    language: 'ഭാഷ',
    appLanguage: 'ആപ്പ് ഭാഷ',
    english: 'ഇംഗ്ലീഷ്',
    tamil: 'തമിഴ്',
  },
  dashboard: {
    title: 'ഡാഷ്ബോർഡ്',
    subtitle: 'ആധി എഞ്ചിൻ സർവീസ്',
    quickActions: 'ദ്രുത പ്രവർത്തനങ്ങൾ',
    productInvoice: 'ഉൽപ്പന്ന ഇൻവോയ്സ്',
    labourInvoices: 'തൊഴിൽ ഇൻവോയ്സുകൾ',
    totalInvoices: 'ആകെ ഇൻവോയ്സുകൾ',
    totalRevenue: 'ആകെ വരുമാനം',
    customers: 'ഉപഭോക്താക്കൾ',
    monthlySummary: 'പ്രതിമാസ സംഗ്രഹം',
    performance: '{{month}} പ്രകടനം',
    recentInvoices: 'സമീപകാല ഇൻവോയ്സുകൾ',
    viewAll: 'എല്ലാം കാണുക',
    noInvoicesYet: 'ഇതുവരെ ഇൻവോയ്സുകൾ ഇല്ല',
    unknownCustomer: 'അജ്ഞാത ഉപഭോക്താവ്',
    changeThisMonth: 'ഈ മാസം {{value}}%',
  },
  customerList: {
    title: 'ഉപഭോക്താക്കൾ',
    record: 'റെക്കോർഡ്',
    records: 'റെക്കോർഡുകൾ',
    searchPlaceholder: 'പേര്, മൊബൈൽ അല്ലെങ്കിൽ വിലാസം ഉപയോഗിച്ച് തിരയുക',
    resultsFor: '"{{query}}" എന്നതിനായി {{count}} {{resultWord}}',
    result: 'ഫലം',
    results: 'ഫലങ്ങൾ',
    noResultsFound: 'ഫലങ്ങളൊന്നും കണ്ടെത്തിയില്ല',
    noCustomersYet: 'ഇതുവരെ ഉപഭോക്താക്കൾ ഇല്ല',
    nothingMatched: '"{{query}}" എന്നതിന് പൊരുത്തപ്പെടുന്നില്ല',
    tapToAdd: 'നിങ്ങളുടെ ആദ്യ ഉപഭോക്താവിനെ ചേർക്കാൻ + അമർത്തുക',
    deleteCustomerTitle: 'ഉപഭോക്താവിനെ ഇല്ലാതാക്കണോ?',
    deleteCustomerMessage:
      '"{{name}}" സ്ഥിരമായി നീക്കം ചെയ്യപ്പെടും. ഇത് തിരിച്ചെടുക്കാൻ കഴിയില്ല.',
  },
  createCustomer: {
    editTitle: 'ഉപഭോക്താവിനെ എഡിറ്റ് ചെയ്യുക',
    addTitle: 'ഉപഭോക്താവിനെ ചേർക്കുക',
    subtitle: 'ആധി എഞ്ചിൻ സർവീസ്',
    heading: 'ഉപഭോക്തൃ വിവരങ്ങൾ',
    descriptionEdit: 'താഴെ ഉപഭോക്തൃ വിവരങ്ങൾ അപ്‌ഡേറ്റ് ചെയ്യുക',
    descriptionAdd:
      'പുതിയ ഉപഭോക്താവിനെ ചേർക്കാൻ താഴെയുള്ള വിവരങ്ങൾ പൂരിപ്പിക്കുക',
    customerName: 'ഉപഭോക്താവിന്റെ പേര്',
    enterFullName: 'പൂർണ്ണ പേര് നൽകുക',
    mobileNumber: 'മൊബൈൽ നമ്പർ',
    optional: '(ഓപ്ഷണൽ)',
    enter10Digit: '10 അക്ക നമ്പർ നൽകുക',
    address: 'വിലാസം',
    enterAddress: 'തെരുവ്, നഗരം, സംസ്ഥാനം... നൽകുക',
    updating: 'അപ്‌ഡേറ്റ് ചെയ്യുന്നു....',
    saving: 'സേവ് ചെയ്യുന്നു....',
    updateCustomer: 'ഉപഭോക്താവിനെ അപ്‌ഡേറ്റ് ചെയ്യുക',
    saveCustomer: 'ഉപഭോക്താവിനെ സേവ് ചെയ്യുക',
    discardTitle: 'മാറ്റങ്ങൾ ഉപേക്ഷിക്കണോ?',
    discardMessage: 'നിങ്ങളുടെ മാറ്റങ്ങൾ സേവ് ചെയ്യപ്പെടില്ല. പുറത്തുകടക്കണോ?',
    discard: 'ഉപേക്ഷിക്കുക',
    keepEditing: 'എഡിറ്റിംഗ് തുടരുക',
    deleteCustomerTitle: 'ഉപഭോക്താവിനെ ഇല്ലാതാക്കണോ?',
    deleteCustomerMessage:
      '"{{name}}" സ്ഥിരമായി നീക്കം ചെയ്യപ്പെടും. ഇത് തിരിച്ചെടുക്കാൻ കഴിയില്ല.',
    nameRequired: 'ഉപഭോക്താവിന്റെ പേര് ആവശ്യമാണ്',
    mobileDigits: 'മൊബൈൽ നമ്പർ 10 അക്കമായിരിക്കണം',
    addressRequired: 'വിലാസം ആവശ്യമാണ്',
  },
  invoiceForm: {
    editInvoice: 'ഇൻവോയ്സ് എഡിറ്റ് ചെയ്യുക',
    createInvoice: 'ഇൻവോയ്സ് സൃഷ്ടിക്കുക',
    editLabourInvoice: 'തൊഴിൽ ഇൻവോയ്സ് എഡിറ്റ് ചെയ്യുക',
    createLabourInvoice: 'തൊഴിൽ ഇൻവോയ്സ് സൃഷ്ടിക്കുക',
    customerName: 'ഉപഭോക്താവിന്റെ പേര്',
    paymentReceived: 'പേയ്‌മെന്റ് ലഭിച്ചു',
    paymentMode: 'പേയ്‌മെന്റ് രീതി',
    selectPaymentMode: 'പേയ്‌മെന്റ് രീതി തിരഞ്ഞെടുക്കുക',
    invoiceDate: 'ഇൻവോയ്സ് തീയതി',
    billNo: 'ബിൽ നമ്പർ',
    addProduct: 'ഉൽപ്പന്നം ചേർക്കുക',
    addItem: 'ഇനം ചേർക്കുക',
    productNamePlaceholder: 'ഉൽപ്പന്നത്തിന്റെ പേര്',
    descriptionPlaceholder: 'വിവരണം',
    amountPlaceholder: 'തുക',
    qty: 'അളവ്',
    unitPrice: 'യൂണിറ്റ് വില',
    addProductBtn: '＋ ഉൽപ്പന്നം ചേർക്കുക',
    addItemBtn: '＋ ഇനം ചേർക്കുക',
    items: 'ഇനങ്ങൾ ({{count}})',
    save: 'സേവ് ചെയ്യുക',
    grandTotal: 'ആകെ തുക',
    updateBill: 'ബിൽ അപ്‌ഡേറ്റ് ചെയ്യുക',
    generateBill: 'ബിൽ സൃഷ്ടിക്കുക',
    pleaseSelectCustomer: 'ദയവായി ഉപഭോക്താവിനെ തിരഞ്ഞെടുക്കുക',
    addAtLeastOneProduct: 'കുറഞ്ഞത് ഒരു ഉൽപ്പന്നമെങ്കിലും ചേർക്കുക',
    addAtLeastOneItem: 'കുറഞ്ഞത് ഒരു ഇനമെങ്കിലും ചേർക്കുക',
    invoiceUpdated: 'ഇൻവോയ്സ് വിജയകരമായി അപ്‌ഡേറ്റ് ചെയ്തു',
    invoiceCreated: 'ഇൻവോയ്സ് സൃഷ്ടിച്ചു',
    labourInvoiceUpdated: 'തൊഴിൽ ഇൻവോയ്സ് വിജയകരമായി അപ്‌ഡേറ്റ് ചെയ്തു',
    labourInvoiceCreated: 'തൊഴിൽ ഇൻവോയ്സ് സൃഷ്ടിച്ചു',
  },
  invoiceList: {
    billNoPrefix: 'ബിൽ നമ്പർ :{{no}}',
    total: 'ആകെ',
    unknownCustomer: 'അജ്ഞാത ഉപഭോക്താവ്',
    items: 'ഇനങ്ങൾ',
    itemCount: '{{count}} {{itemWord}}',
    item: 'ഇനം',
    itemsWord: 'ഇനങ്ങൾ',
    tapToView: 'ഇൻവോയ്സ് വിശദാംശങ്ങൾ കാണാൻ അമർത്തുക',
    noInvoicesFound: 'ഇൻവോയ്സുകൾ ഒന്നും കണ്ടെത്തിയില്ല',
    createFirst: 'ആരംഭിക്കാൻ നിങ്ങളുടെ ആദ്യ ഇൻവോയ്സ് സൃഷ്ടിക്കുക.',
    adjustFilters: 'ഫിൽട്ടറുകളോ തിരയൽ വാക്കുകളോ മാറ്റി ശ്രമിക്കുക.',
    clearAllFilters: 'എല്ലാ ഫിൽട്ടറുകളും മായ്ക്കുക',
    searchPlaceholder: 'കോഡ്, ഉപഭോക്താവ് അല്ലെങ്കിൽ മൊബൈൽ ഉപയോഗിച്ച് തിരയുക...',
    filters: 'ഫിൽട്ടറുകൾ',
    paymentStatus: 'പേയ്‌മെന്റ് നില',
    invoiceType: 'ഇൻവോയ്സ് തരം',
    dateRange: 'തീയതി പരിധി',
    clearAll: 'എല്ലാം മായ്ക്കുക',
    applyFilters: 'ഫിൽട്ടറുകൾ പ്രയോഗിക്കുക',
    all: 'എല്ലാം',
    product: 'ഉൽപ്പന്നം',
    labour: 'തൊഴിൽ',
  },
  invoicePreview: {
    title: 'ഇൻവോയ്സ് പ്രിവ്യൂ',
    companySubtitle: 'ആധി എഞ്ചിൻ കെയർ',
    billNo: 'ബിൽ നമ്പർ:',
    date: 'തീയതി:',
    customerDetails: 'ഉപഭോക്തൃ വിവരങ്ങൾ',
    to: 'ലേക്ക്',
    noPhoneAvailable: 'ഫോൺ നമ്പർ ലഭ്യമല്ല',
    paymentMode: 'പേയ്‌മെന്റ് രീതി',
    sNo: 'ക്രമ നമ്പർ',
    descriptionCol: 'വിവരണം',
    qty: 'അളവ്',
    rate: 'നിരക്ക്',
    amount: 'തുക',
    total: 'ആകെ',
    amountInWords: 'തുക വാക്കുകളിൽ',
    sign: 'ഒപ്പ്',
    markAsPaid: 'പേയ്‌മെന്റ് ചെയ്തതായി അടയാളപ്പെടുത്തുക',
    generatingPdf: 'PDF സൃഷ്ടിക്കുന്നു...',
    previewPdf: 'PDF പ്രിവ്യൂ',
    selectPaymentMode: 'പേയ്‌മെന്റ് രീതി തിരഞ്ഞെടുക്കുക',
    updatePaymentMode: 'പേയ്‌മെന്റ് രീതി അപ്‌ഡേറ്റ് ചെയ്യുക',
    updating: 'അപ്‌ഡേറ്റ് ചെയ്യുന്നു...',
    confirm: 'സ്ഥിരീകരിക്കുക',
    invoicePdf: 'ഇൻവോയ്സ് PDF',
    share: 'പങ്കിടുക',
    download: 'ഡൗൺലോഡ് ചെയ്യുക',
    saving: 'സേവ് ചെയ്യുന്നു...',
    pdfNotReady: 'PDF ഇതുവരെ തയ്യാറായിട്ടില്ല.',
    pdfNotReadyShort: 'PDF തയ്യാറായിട്ടില്ല.',
    failedToGeneratePdf: 'PDF സൃഷ്ടിക്കാൻ കഴിഞ്ഞില്ല.',
    failedToGeneratePdfRetry:
      'PDF സൃഷ്ടിക്കാൻ കഴിഞ്ഞില്ല. ദയവായി വീണ്ടും ശ്രമിക്കുക.',
    savedTitle: 'സേവ് ചെയ്തു!',
    savedMessage: 'ഇൻവോയ്സ് Downloads ഫോൾഡറിൽ സേവ് ചെയ്തു.',
    failedToSavePdf: 'PDF സേവ് ചെയ്യാൻ കഴിഞ്ഞില്ല.',
    shareFailedTitle: 'പങ്കിടൽ പരാജയപ്പെട്ടു',
    shareFailedMessage: 'ഇൻവോയ്സ് PDF പങ്കിടാൻ കഴിഞ്ഞില്ല.',
    printFailedTitle: 'പ്രിന്റ് പരാജയപ്പെട്ടു',
    printFailedMessage: 'പ്രിന്റ് ഡയലോഗ് തുറക്കാൻ കഴിഞ്ഞില്ല.',
    unableToOpenDialer: 'ഡയലർ തുറക്കാൻ കഴിഞ്ഞില്ല',
    paymentUpdated: 'ഇൻവോയ്സ് പണമടച്ചതായി അടയാളപ്പെടുത്തി',
    failedToUpdatePayment: 'പേയ്‌മെന്റ് നില അപ്‌ഡേറ്റ് ചെയ്യാൻ കഴിഞ്ഞില്ല',
    couldNotRenderPdf: 'PDF പ്രിവ്യൂ കാണിക്കാൻ കഴിഞ്ഞില്ല.',
  },
  notifications: {
    sectionTitle: 'അറിയിപ്പുകൾ',
    paymentReminders: 'അറിയിപ്പുകൾ',
    paymentRemindersDescription:
      'പേയ്‌മെന്റ് ഓർമ്മപ്പെടുത്തലുകളും പ്രതിവാര സംഗ്രഹവും ഇൻവോയ്സ് അറിയിപ്പുകളും ലഭിക്കുക.',
    permissionTitle: 'അറിയിപ്പുകൾ ഓഫ് ആണ്',
    permissionMessage:
      'പേയ്‌മെന്റ് ഓർമ്മപ്പെടുത്തലുകൾ ലഭിക്കാൻ ഉപകരണ ക്രമീകരണങ്ങളിൽ അറിയിപ്പുകൾ അനുവദിക്കുക.',
    setupFailed: 'പേയ്‌മെന്റ് ഓർമ്മപ്പെടുത്തലുകൾ സജ്ജമാക്കാനായില്ല. വീണ്ടും ശ്രമിക്കുക.',
    channelName: 'പേയ്‌മെന്റ് ഓർമ്മപ്പെടുത്തലുകൾ',
    unknownCustomer: 'നിങ്ങളുടെ ഉപഭോക്താവ്',
    pendingTitle: 'പേയ്‌മെന്റ് ഇപ്പോഴും ബാക്കിയുണ്ട്',
    pendingMessage:
      '{{customer}}ന്റെ ഇൻവോയ്സ് #{{billNo}} ({{amount}}) പേയ്‌മെന്റ് {{days}} ദിവസമായിട്ടും ലഭിച്ചിട്ടില്ല.',
    weeklyTitle: 'പ്രതിവാര ബാക്കി പേയ്‌മെന്റ് സംഗ്രഹം',
    weeklyMessage:
      '{{count}} ഇൻവോയ്സുകളിലായി ആകെ {{amount}} ലഭിക്കാനുണ്ട്.',
    invoiceCreatedTitle: 'പുതിയ ഇൻവോയ്സ് സൃഷ്ടിച്ചു',
    invoiceCreatedMessage:
      '{{customer}}നുള്ള {{amount}}-ന്റെ ഇൻവോയ്സ് #{{billNo}} സേവ് ചെയ്തു.',
    paymentReceivedTitle: 'പേയ്‌മെന്റ് ലഭിച്ചു',
    paymentReceivedMessage:
      '{{customer}}ന്റെ ഇൻവോയ്സ് #{{billNo}}-ന് {{amount}} ലഭിച്ചതായി രേഖപ്പെടുത്തി.',
  },
};
