export default {
  common: {
    cancel: 'ரத்து செய்',
    delete: 'நீக்கு',
    save: 'சேமி',
    edit: 'திருத்து',
    update: 'புதுப்பி',
    close: 'மூடு',
    error: 'பிழை',
    success: 'வெற்றி',
    selectCustomer: 'வாடிக்கையாளரைத் தேர்ந்தெடுக்கவும்',
    noCustomersFound: 'வாடிக்கையாளர்கள் இல்லை.',
    selectCustomerTitle: 'வாடிக்கையாளரைத் தேர்ந்தெடுக்கவும்',
    cash: 'Cash',
    upi: 'UPI',
    card: 'Card',
    netBanking: 'Net Banking',
    paid: 'செலுத்தப்பட்டது',
    pending: 'நிலுவையில்',
    required: 'தேவை',
    deleteInvoiceTitle: 'விலைப்பட்டியலை நீக்கவா',
    deleteInvoiceMessage: 'இந்த விலைப்பட்டியலை நீக்க விரும்புகிறீர்களா?',
    invoiceDeleted: 'விலைப்பட்டியல் வெற்றிகரமாக நீக்கப்பட்டது',
    failedDeleteInvoice: 'விலைப்பட்டியலை நீக்க முடியவில்லை ',
  },

  stepIndicator: {
    customer: 'வாடிக்கையாளர்',
    products: 'பொருட்கள்',
    summary: 'சுருக்கம்',
  },

  bottomNav: {
    home: 'முகப்பு',
    create: 'உருவாக்கு',
    labour: 'கூலி',
    invoices: 'விலைப்பட்டியல்கள்',
  },

  splash: {
    companyLine1: 'ஆதி இன்ஜின்',
    companyLine2: 'கேர்',
    tagline: 'ஆன்லைன் பில்லிங் சிஸ்டம்',
    loadingTexts: [
      'கணினியைத் தொடங்குகிறது...',
      'சேவைகளை இணைக்கிறது...',
      'தொகுதிகளை ஏற்றுகிறது...',
      'டாஷ்போர்டைத் தயார்படுத்துகிறது...',
      'கிட்டத்தட்ட தயார்...',
    ],
  },

  login: {
    companyName: 'ஆதி இன்ஜின் கேர்',
    welcomeBack: 'மீண்டும் வருக',
    enterPin: 'தொடர 4 இலக்க பின் எண்ணை உள்ளிடவும்',
    somethingWrong: 'ஏதோ தவறு நடந்தது',
    wrongPin: 'தவறான பின்',
    onlineBillingSystem: 'ஆன்லைன் பில்லிங் சிஸ்டம்',
    designedBy: 'வடிவமைத்து உருவாக்கியவர் சண்முகப்பிரியா ஐயப்பன்',
    deleteKey: 'நீக்கு',
    keyLabel: 'விசை {{label}}',
  },

  settings: {
    title: 'அமைப்புகள்',
    dataManagement: 'தரவு மேலாண்மை',
    backupData: 'தரவு காப்புப்பிரதி',
    exportInvoices: 'விலைப்பட்டியல்களை ஏற்றுமதி செய் (.JSON)',
    restoreBackup: 'காப்புப்பிரதியை மீட்டமை',
    systemMaintenance: 'கணினி பராமரிப்பு',
    deleteAllReports: 'அனைத்து அறிக்கைகளையும் நீக்கு',
    logout: 'வெளியேறு',
    logoutConfirmTitle: 'உறுதியாக இருக்கிறீர்களா?',
    logoutConfirmMessage: 'நீங்கள் கணினியிலிருந்து வெளியேற்றப்படுவீர்கள்.',
    footer: 'ஆதி இன்ஜின் சர்வீஸ் v1.0.0 (பில்ட் 2026)',
    language: 'மொழி',
    appLanguage: 'பயன்பாட்டு மொழி',
    english: 'English',
    tamil: 'தமிழ்',
  },

  dashboard: {
    title: 'டாஷ்போர்டு',
    subtitle: 'ஆதி இன்ஜின் சர்வீஸ்',
    quickActions: 'விரைவு செயல்கள்',
    productInvoice: 'பொருள் விலைப்பட்டியல்',
    labourInvoices: 'கூலி விலைப்பட்டியல்கள்',
    totalInvoices: 'மொத்த விலைப்பட்டியல்கள்',
    totalRevenue: 'மொத்த வருவாய்',
    customers: 'வாடிக்கையாளர்கள்',
    monthlySummary: 'மாதாந்திர சுருக்கம்',
    performance: '{{month}} செயல்திறன்',
    recentInvoices: 'சமீபத்திய விலைப்பட்டியல்கள்',
    viewAll: 'அனைத்தையும் காண்க',
    noInvoicesYet: 'இதுவரை விலைப்பட்டியல்கள் இல்லை',
    unknownCustomer: 'தெரியாத வாடிக்கையாளர்',
    changeThisMonth: '{{value}}% இந்த மாதம்',
  },

  customerList: {
    title: 'வாடிக்கையாளர்கள்',
    record: 'பதிவு',
    records: 'பதிவுகள்',
    searchPlaceholder: 'பெயர், மொபைல் அல்லது முகவரி மூலம் தேடுங்கள்',
    resultsFor: '"{{query}}" க்கு {{count}} {{resultWord}}',
    result: 'முடிவு',
    results: 'முடிவுகள்',
    noResultsFound: 'முடிவுகள் இல்லை',
    noCustomersYet: 'இதுவரை வாடிக்கையாளர்கள் இல்லை',
    nothingMatched: '"{{query}}" க்கு எதுவும் பொருந்தவில்லை',
    tapToAdd: 'உங்கள் முதல் வாடிக்கையாளரைச் சேர்க்க + ஐத் தட்டவும்',
    deleteCustomerTitle: 'வாடிக்கையாளரை நீக்கவா?',
    deleteCustomerMessage:
      '"{{name}}" நிரந்தரமாக அகற்றப்படும். இதை மாற்ற முடியாது.',
  },

  createCustomer: {
    editTitle: 'வாடிக்கையாளரைத் திருத்து',
    addTitle: 'வாடிக்கையாளரைச் சேர்',
    subtitle: 'ஆதி இன்ஜின் சர்வீஸ்',
    heading: 'வாடிக்கையாளர் விவரங்கள்',
    descriptionEdit: 'கீழே உள்ள வாடிக்கையாளர் தகவலைப் புதுப்பிக்கவும்',
    descriptionAdd:
      'புதிய வாடிக்கையாளரைச் சேர்க்க கீழே உள்ள விவரங்களை நிரப்பவும்',
    customerName: 'வாடிக்கையாளர் பெயர்',
    enterFullName: 'முழு பெயரை உள்ளிடவும்',
    mobileNumber: 'மொபைல் எண்',
    optional: '(விருப்பத்தேர்வு)',
    enter10Digit: '10 இலக்க எண்ணை உள்ளிடவும்',
    address: 'முகவரி',
    enterAddress: 'தெரு, நகரம், மாநிலத்தை உள்ளிடவும்...',
    updating: 'புதுப்பிக்கிறது....',
    saving: 'சேமிக்கிறது....',
    updateCustomer: 'வாடிக்கையாளரைப் புதுப்பி',
    saveCustomer: 'வாடிக்கையாளரைச் சேமி',
    discardTitle: 'மாற்றங்களை நிராகரிக்கவா?',
    discardMessage:
      'உங்கள் மாற்றங்கள் சேமிக்கப்படாது. வெளியேற விரும்புகிறீர்களா?',
    discard: 'நிராகரி',
    keepEditing: 'தொடர்ந்து திருத்து',
    deleteCustomerTitle: 'வாடிக்கையாளரை நீக்கவா?',
    deleteCustomerMessage:
      '"{{name}}" நிரந்தரமாக அகற்றப்படும். இதை மாற்ற முடியாது.',
    nameRequired: 'வாடிக்கையாளர் பெயர் தேவை',
    mobileDigits: 'மொபைல் எண் 10 இலக்கங்களாக இருக்க வேண்டும்',
    addressRequired: 'முகவரி தேவை',
  },

  invoiceForm: {
    editInvoice: 'விலைப்பட்டியலைத் திருத்து',
    createInvoice: 'விலைப்பட்டியல் உருவாக்கு',
    editLabourInvoice: 'கூலி விலைப்பட்டியலைத் திருத்து',
    createLabourInvoice: 'கூலி விலைப்பட்டியல் உருவாக்கு',
    customerName: 'வாடிக்கையாளர் பெயர்',
    paymentReceived: 'பணம் பெறப்பட்டது',
    paymentMode: 'கட்டண முறை',
    selectPaymentMode: 'கட்டண முறையைத் தேர்ந்தெடுக்கவும்',
    invoiceDate: 'விலைப்பட்டியல் தேதி',
    billNo: 'பில் எண்',
    addProduct: 'பொருளைச் சேர்',
    addItem: 'பொருச் சேர்',
    productNamePlaceholder: 'பொருளின் பெயர்',
    descriptionPlaceholder: 'விவரம்',
    amountPlaceholder: 'தொகை',
    qty: 'எண்ணிக்கை',
    unitPrice: 'அலகு விலை',
    addProductBtn: '＋ பொருளைச் சேர்',
    addItemBtn: '＋ பொருளைச் சேர்',
    items: 'பொருட்கள் ({{count}})',
    save: 'சேமி',
    grandTotal: 'மொத்த தொகை',
    updateBill: 'பில்லைப் புதுப்பி',
    generateBill: 'பில் உருவாக்கு',
    pleaseSelectCustomer: 'வாடிக்கையாளரைத் தேர்ந்தெடுக்கவும்',
    addAtLeastOneProduct: 'குறைந்தது ஒரு பொருளையாவது சேர்க்கவும்',
    addAtLeastOneItem: 'குறைந்தது ஒரு பொருளையாவது சேர்க்கவும்',
    invoiceUpdated: 'விலைப்பட்டியல் வெற்றிகரமாக புதுப்பிக்கப்பட்டது',
    invoiceCreated: 'விலைப்பட்டியல் உருவாக்கப்பட்டது ',
    labourInvoiceUpdated:
      'கூலி விலைப்பட்டியல் வெற்றிகரமாக புதுப்பிக்கப்பட்டது ',
    labourInvoiceCreated: 'கூலி விலைப்பட்டியல் உருவாக்கப்பட்டது ',
  },

  invoiceList: {
    billNoPrefix: 'பில் எண் :{{no}}',
    total: 'மொத்தம்',
    unknownCustomer: 'தெரியாத வாடிக்கையாளர்',
    items: 'பொருட்கள்',
    itemCount: '{{count}} {{itemWord}}',
    item: 'பொருலள்',
    itemsWord: 'பொருட்கள்',
    tapToView: 'விலைப்பட்டியல் விவரங்களைக் காண தட்டவும்',
    noInvoicesFound: 'விலைப்பட்டியல்கள் இல்லை',
    createFirst: 'தொடங்க உங்கள் முதல் விலைப்பட்டியலை உருவாக்கவும்.',
    adjustFilters: 'உங்கள் வடிகட்டிகள் அல்லது தேடல் வினவலை சரிசெய்யவும்.',
    clearAllFilters: 'அனைத்து வடிகட்டிகளையும் அழி',
    searchPlaceholder:
      'குறியீடு, வாடிக்கையாளர் அல்லது மொபைல் மூலம் தேடுங்கள்...',
    filters: 'வடிகட்டிகள்',
    paymentStatus: 'கட்டண நிலை',
    invoiceType: 'விலைப்பட்டியல் வகை',
    dateRange: 'தேதி வரம்பு',
    clearAll: 'அனைத்தையும் அழி',
    applyFilters: 'வடிகட்டிகளைப் பயன்படுத்து',
    all: 'அனைத்தும்',
    product: 'பொருள்',
    labour: 'கூலி',
  },

  invoicePreview: {
    title: 'விலைப்பட்டியல் முன்னோட்டம்',
    companySubtitle: 'ஆதி இன்ஜின் கேர்',
    billNo: 'பில் எண்:',
    date: 'தேதி:',
    customerDetails: 'வாடிக்கையாளர் விவரங்கள்',
    to: 'பெறுநர்',
    noPhoneAvailable: 'தொலைபேசி எண் இல்லை',
    paymentMode: 'கட்டண முறை',
    sNo: 'வ.எண்',
    descriptionCol: 'விவரம்',
    qty: 'எண்ணிக்கை',
    rate: 'விலை',
    amount: 'தொகை',
    total: 'மொத்தம்',
    amountInWords: 'வார்த்தைகளில் தொகை',
    sign: 'கையொப்பம்',
    markAsPaid: 'செலுத்தப்பட்டதாகக் குறி',
    generatingPdf: 'PDF உருவாக்குகிறது...',
    previewPdf: 'PDF முன்னோட்டம்',
    selectPaymentMode: 'கட்டண முறையைத் தேர்ந்தெடுக்கவும்',
    updatePaymentMode: 'கட்டண முறையைப் புதுப்பி',
    updating: 'புதுப்பிக்கிறது...',
    confirm: 'உறுதிசெய்',
    invoicePdf: 'விலைப்பட்டியல் PDF',
    share: 'பகிர்',
    download: 'பதிவிறக்கு',
    saving: 'சேமிக்கிறது...',
    pdfNotReady: 'PDF இன்னும் தயாராக இல்லை.',
    pdfNotReadyShort: 'PDF தயாராக இல்லை.',
    failedToGeneratePdf: 'PDF உருவாக்க முடியவில்லை.',
    failedToGeneratePdfRetry:
      'PDF உருவாக்க முடியவில்லை. மீண்டும் முயற்சிக்கவும்.',
    savedTitle: 'சேமிக்கப்பட்டது!',
    savedMessage: 'விலைப்பட்டியல் பதிவிறக்கங்கள் கோப்புறையில் சேமிக்கப்பட்டது.',
    failedToSavePdf: 'PDF ஐ சேமிக்க முடியவில்லை.',
    shareFailedTitle: 'பகிர்வு தோல்வியடைந்தது',
    shareFailedMessage: 'விலைப்பட்டியல் PDF ஐ பகிர முடியவில்லை.',
    printFailedTitle: 'அச்சிடல் தோல்வியடைந்தது',
    printFailedMessage: 'அச்சு உரையாடலைத் திறக்க முடியவில்லை.',
    unableToOpenDialer: 'டயலரைத் திறக்க முடியவில்லை',
    paymentUpdated: 'விலைப்பட்டியல் செலுத்தப்பட்டதாகக் குறிக்கப்பட்டது ',
    failedToUpdatePayment: 'கட்டண நிலையைப் புதுப்பிக்க முடியவில்லை ',
    couldNotRenderPdf: 'PDF முன்னோட்டத்தைக் காட்ட முடியவில்லை.',
  },
};
