export default {
  "common": {
    "cancel": "రద్దు చేయండి",
    "delete": "తొలగించండి",
    "save": "సేవ్ చేయండి",
    "edit": "సవరించండి",
    "update": "అప్‌డేట్ చేయండి",
    "close": "మూసివేయండి",
    "error": "లోపం",
    "success": "విజయం",
    "selectCustomer": "కస్టమర్‌ను ఎంచుకోండి",
    "noCustomersFound": "కస్టమర్లు ఎవరూ కనుగొనబడలేదు.",
    "selectCustomerTitle": "కస్టమర్‌ను ఎంచుకోండి",
    "cash": "నగదు",
    "upi": "UPI",
    "card": "కార్డ్",
    "netBanking": "నెట్ బ్యాంకింగ్",
    "paid": "చెల్లించబడింది",
    "pending": "పెండింగ్",
    "required": "అవసరం",
    "deleteInvoiceTitle": "ఇన్‌వాయిస్ తొలగించండి",
    "deleteInvoiceMessage": "మీరు నిజంగా ఈ ఇన్‌వాయిస్‌ను తొలగించాలనుకుంటున్నారా?",
    "invoiceDeleted": "ఇన్‌వాయిస్ విజయవంతంగా తొలగించబడింది",
    "failedDeleteInvoice": "ఇన్‌వాయిస్ తొలగించడం విఫలమైంది"
  },
  "stepIndicator": {
    "customer": "కస్టమర్",
    "products": "ఉత్పత్తులు",
    "summary": "సారాంశం"
  },
  "bottomNav": {
    "home": "హోమ్",
    "create": "సృష్టించండి",
    "labour": "లేబర్",
    "invoices": "ఇన్‌వాయిస్‌లు"
  },
  "splash": {
    "companyLine1": "ఆధి ఇంజిన్",
    "companyLine2": "సర్వీసెస్",
    "tagline": "ఆన్‌లైన్ బిల్లింగ్ సిస్టమ్",
    "loadingTexts": [
      "సిస్టమ్ ప్రారంభిస్తోంది...",
      "సర్వీసులకు కనెక్ట్ అవుతోంది...",
      "మాడ్యూల్స్ లోడ్ అవుతున్నాయి...",
      "డ్యాష్‌బోర్డ్ సిద్ధం చేస్తోంది...",
      "దాదాపు సిద్ధంగా ఉంది..."
    ]
  },
  "login": {
    "companyName": "ఆధి ఇంజిన్ సర్వీసెస్",
    "welcomeBack": "తిరిగి స్వాగతం",
    "enterPin": "కొనసాగించడానికి మీ 4 అంకెల PIN నమోదు చేయండి",
    "somethingWrong": "ఏదో తప్పు జరిగింది",
    "wrongPin": "తప్పు PIN",
    "onlineBillingSystem": "ఆన్‌లైన్ బిల్లింగ్ సిస్టమ్",
    "designedBy": "Shanmugapriya Iyappan ద్వారా డిజైన్ & డెవలప్ చేయబడింది",
    "deleteKey": "తొలగించండి",
    "keyLabel": "కీ {{label}}"
  },
  "settings": {
    "title": "సెట్టింగ్స్",
    "dataManagement": "డేటా నిర్వహణ",
    "backupData": "డేటా బ్యాకప్",
    "exportInvoices": "ఇన్‌వాయిస్‌లను ఎగుమతి చేయండి (.JSON)",
    "restoreBackup": "బ్యాకప్‌ను పునరుద్ధరించండి",
    "systemMaintenance": "సిస్టమ్ నిర్వహణ",
    "deleteAllReports": "అన్ని రిపోర్ట్‌లను తొలగించండి",
    "logout": "లాగ్ అవుట్",
    "logoutConfirmTitle": "మీరు ఖచ్చితంగా లాగ్ అవుట్ చేయాలనుకుంటున్నారా?",
    "logoutConfirmMessage": "మీరు సిస్టమ్ నుండి లాగ్ అవుట్ అవుతారు.",
    "footer": "ఆధి ఇంజిన్ సర్వీస్ v1.0.0 (బిల్డ్ 2026)",
    "language": "భాష",
    "appLanguage": "యాప్ భాష",
    "english": "ఇంగ్లీష్",
    "tamil": "తమిళం"
  },
  "dashboard": {
    "title": "డ్యాష్‌బోర్డ్",
    "subtitle": "ఆధి ఇంజిన్ సర్వీస్",
    "quickActions": "త్వరిత చర్యలు",
    "productInvoice": "ఉత్పత్తి ఇన్‌వాయిస్",
    "labourInvoices": "లేబర్ ఇన్‌వాయిస్‌లు",
    "totalInvoices": "మొత్తం ఇన్‌వాయిస్‌లు",
    "totalRevenue": "మొత్తం ఆదాయం",
    "customers": "కస్టమర్లు",
    "monthlySummary": "నెలవారీ సారాంశం",
    "performance": "{{month}} పనితీరు",
    "recentInvoices": "ఇటీవలి ఇన్‌వాయిస్‌లు",
    "viewAll": "అన్నీ చూడండి",
    "noInvoicesYet": "ఇంకా ఇన్‌వాయిస్‌లు లేవు",
    "unknownCustomer": "తెలియని కస్టమర్",
    "changeThisMonth": "ఈ నెల {{value}}%"
  },
  "customerList": {
    "title": "కస్టమర్లు",
    "record": "రికార్డ్",
    "records": "రికార్డ్‌లు",
    "searchPlaceholder": "పేరు, మొబైల్ లేదా చిరునామాతో శోధించండి",
    "resultsFor": "\"{{query}}\" కోసం {{count}} {{resultWord}}",
    "result": "ఫలితం",
    "results": "ఫలితాలు",
    "noResultsFound": "ఫలితాలు ఏవీ కనుగొనబడలేదు",
    "noCustomersYet": "ఇంకా కస్టమర్లు లేరు",
    "nothingMatched": "\"{{query}}\"కి సరిపోలేది ఏదీ లేదు",
    "tapToAdd": "మీ మొదటి కస్టమర్‌ను జోడించడానికి + నొక్కండి",
    "deleteCustomerTitle": "కస్టమర్‌ను తొలగించాలా?",
    "deleteCustomerMessage": "\"{{name}}\" శాశ్వతంగా తొలగించబడుతుంది. దీన్ని తిరిగి పొందలేరు."
  },
  "createCustomer": {
    "editTitle": "కస్టమర్‌ను సవరించండి",
    "addTitle": "కస్టమర్‌ను జోడించండి",
    "subtitle": "ఆధి ఇంజిన్ సర్వీస్",
    "heading": "కస్టమర్ వివరాలు",
    "descriptionEdit": "క్రింద కస్టమర్ సమాచారాన్ని అప్‌డేట్ చేయండి",
    "descriptionAdd": "కొత్త కస్టమర్‌ను జోడించడానికి క్రింది వివరాలను నమోదు చేయండి",
    "customerName": "కస్టమర్ పేరు",
    "enterFullName": "పూర్తి పేరు నమోదు చేయండి",
    "mobileNumber": "మొబైల్ నంబర్",
    "optional": "(ఐచ్ఛికం)",
    "enter10Digit": "10 అంకెల నంబర్ నమోదు చేయండి",
    "address": "చిరునామా",
    "enterAddress": "వీధి, నగరం, రాష్ట్రం... నమోదు చేయండి",
    "updating": "అప్‌డేట్ అవుతోంది....",
    "saving": "సేవ్ అవుతోంది....",
    "updateCustomer": "కస్టమర్‌ను అప్‌డేట్ చేయండి",
    "saveCustomer": "కస్టమర్‌ను సేవ్ చేయండి",
    "discardTitle": "మార్పులను విస్మరించాలా?",
    "discardMessage": "మీ మార్పులు సేవ్ చేయబడవు. మీరు బయటకు వెళ్లాలనుకుంటున్నారా?",
    "discard": "విస్మరించండి",
    "keepEditing": "ఎడిటింగ్ కొనసాగించండి",
    "deleteCustomerTitle": "కస్టమర్‌ను తొలగించాలా?",
    "deleteCustomerMessage": "\"{{name}}\" శాశ్వతంగా తొలగించబడుతుంది. దీన్ని తిరిగి పొందలేరు.",
    "nameRequired": "కస్టమర్ పేరు అవసరం",
    "mobileDigits": "మొబైల్ నంబర్ 10 అంకెలు ఉండాలి",
    "addressRequired": "చిరునామా అవసరం"
  },
  "invoiceForm": {
    "editInvoice": "ఇన్‌వాయిస్‌ను సవరించండి",
    "createInvoice": "ఇన్‌వాయిస్‌ను సృష్టించండి",
    "editLabourInvoice": "లేబర్ ఇన్‌వాయిస్‌ను సవరించండి",
    "createLabourInvoice": "లేబర్ ఇన్‌వాయిస్‌ను సృష్టించండి",
    "customerName": "కస్టమర్ పేరు",
    "paymentReceived": "చెల్లింపు అందింది",
    "paymentMode": "చెల్లింపు విధానం",
    "selectPaymentMode": "చెల్లింపు విధానాన్ని ఎంచుకోండి",
    "invoiceDate": "ఇన్‌వాయిస్ తేదీ",
    "billNo": "బిల్ నంబర్",
    "addProduct": "ఉత్పత్తిని జోడించండి",
    "addItem": "ఐటమ్‌ను జోడించండి",
    "productNamePlaceholder": "ఉత్పత్తి పేరు",
    "descriptionPlaceholder": "వివరణ",
    "amountPlaceholder": "మొత్తం",
    "qty": "పరిమాణం",
    "unitPrice": "యూనిట్ ధర",
    "addProductBtn": "＋ ఉత్పత్తిని జోడించండి",
    "addItemBtn": "＋ ఐటమ్‌ను జోడించండి",
    "items": "ఐటమ్‌లు ({{count}})",
    "save": "సేవ్ చేయండి",
    "grandTotal": "మొత్తం",
    "updateBill": "బిల్‌ను అప్‌డేట్ చేయండి",
    "generateBill": "బిల్‌ను రూపొందించండి",
    "pleaseSelectCustomer": "దయచేసి కస్టమర్‌ను ఎంచుకోండి",
    "addAtLeastOneProduct": "కనీసం ఒక ఉత్పత్తిని జోడించండి",
    "addAtLeastOneItem": "కనీసం ఒక ఐటమ్‌ను జోడించండి",
    "invoiceUpdated": "ఇన్‌వాయిస్ విజయవంతంగా అప్‌డేట్ చేయబడింది",
    "invoiceCreated": "ఇన్‌వాయిస్ సృష్టించబడింది",
    "labourInvoiceUpdated": "లేబర్ ఇన్‌వాయిస్ విజయవంతంగా అప్‌డేట్ చేయబడింది",
    "labourInvoiceCreated": "లేబర్ ఇన్‌వాయిస్ సృష్టించబడింది"
  },
  "invoiceList": {
    "billNoPrefix": "బిల్ నంబర్ :{{no}}",
    "total": "మొత్తం",
    "unknownCustomer": "తెలియని కస్టమర్",
    "items": "ఐటమ్‌లు",
    "itemCount": "{{count}} {{itemWord}}",
    "item": "ఐటమ్",
    "itemsWord": "ఐటమ్‌లు",
    "tapToView": "ఇన్‌వాయిస్ వివరాలను చూడటానికి నొక్కండి",
    "noInvoicesFound": "ఇన్‌వాయిస్‌లు ఏవీ కనుగొనబడలేదు",
    "createFirst": "ప్రారంభించడానికి మీ మొదటి ఇన్‌వాయిస్‌ను సృష్టించండి.",
    "adjustFilters": "ఫిల్టర్‌లు లేదా శోధనను మార్చి ప్రయత్నించండి.",
    "clearAllFilters": "అన్ని ఫిల్టర్‌లను క్లియర్ చేయండి",
    "searchPlaceholder": "కోడ్, కస్టమర్ లేదా మొబైల్‌తో శోధించండి...",
    "filters": "ఫిల్టర్‌లు",
    "paymentStatus": "చెల్లింపు స్థితి",
    "invoiceType": "ఇన్‌వాయిస్ రకం",
    "dateRange": "తేదీ పరిధి",
    "clearAll": "అన్నీ క్లియర్ చేయండి",
    "applyFilters": "ఫిల్టర్‌లను వర్తింపజేయండి",
    "all": "అన్నీ",
    "product": "ఉత్పత్తి",
    "labour": "లేబర్"
  },
  "invoicePreview": {
    "title": "ఇన్‌వాయిస్ ప్రివ్యూ",
    "companySubtitle": "ఆధి ఇంజిన్ కేర్",
    "billNo": "బిల్ నంబర్:",
    "date": "తేదీ:",
    "customerDetails": "కస్టమర్ వివరాలు",
    "to": "కు",
    "noPhoneAvailable": "ఫోన్ నంబర్ అందుబాటులో లేదు",
    "paymentMode": "చెల్లింపు విధానం",
    "sNo": "క్రమ సంఖ్య",
    "descriptionCol": "వివరణ",
    "qty": "పరిమాణం",
    "rate": "రేటు",
    "amount": "మొత్తం",
    "total": "మొత్తం",
    "amountInWords": "మొత్తం అక్షరాల్లో",
    "sign": "సంతకం",
    "markAsPaid": "చెల్లించినట్లు గుర్తించండి",
    "generatingPdf": "PDF రూపొందుతోంది...",
    "previewPdf": "PDF ప్రివ్యూ",
    "selectPaymentMode": "చెల్లింపు విధానాన్ని ఎంచుకోండి",
    "updatePaymentMode": "చెల్లింపు విధానాన్ని అప్‌డేట్ చేయండి",
    "updating": "అప్‌డేట్ అవుతోంది...",
    "confirm": "నిర్ధారించండి",
    "invoicePdf": "ఇన్‌వాయిస్ PDF",
    "share": "షేర్ చేయండి",
    "download": "డౌన్‌లోడ్ చేయండి",
    "saving": "సేవ్ అవుతోంది...",
    "pdfNotReady": "PDF ఇంకా సిద్ధంగా లేదు.",
    "pdfNotReadyShort": "PDF సిద్ధంగా లేదు.",
    "failedToGeneratePdf": "PDF రూపొందించడం విఫలమైంది.",
    "failedToGeneratePdfRetry": "PDF రూపొందించడం విఫలమైంది. దయచేసి మళ్లీ ప్రయత్నించండి.",
    "savedTitle": "సేవ్ చేయబడింది!",
    "savedMessage": "ఇన్‌వాయిస్ Downloads ఫోల్డర్‌లో సేవ్ చేయబడింది.",
    "failedToSavePdf": "PDF సేవ్ చేయడం విఫలమైంది.",
    "shareFailedTitle": "షేర్ చేయడం విఫలమైంది",
    "shareFailedMessage": "ఇన్‌వాయిస్ PDFను షేర్ చేయడం సాధ్యం కాలేదు.",
    "printFailedTitle": "ప్రింట్ విఫలమైంది",
    "printFailedMessage": "ప్రింట్ డైలాగ్‌ను తెరవడం సాధ్యం కాలేదు.",
    "unableToOpenDialer": "డయలర్‌ను తెరవడం సాధ్యం కాలేదు",
    "paymentUpdated": "ఇన్‌వాయిస్ చెల్లించినట్లు గుర్తించబడింది",
    "failedToUpdatePayment": "చెల్లింపు స్థితిని అప్‌డేట్ చేయడం విఫలమైంది",
    "couldNotRenderPdf": "PDF ప్రివ్యూను చూపించడం సాధ్యం కాలేదు."
  }
}